/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConseilItStrategiqueRouteImport } from './routes/conseil-it-strategique'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcingRecrutementItRouteImport } from './routes/sourcing-recrutement-it'
import { Route as CybersecuriteIndexRouteImport } from './routes/cybersecurite/index'
import { Route as CybersecuriteGrcRouteImport } from './routes/cybersecurite/grc'
import { Route as CybersecuriteSecuriteManageeRouteImport } from './routes/cybersecurite/securite-managee'
import { Route as CybersecuriteTestIntrusionAuditRouteImport } from './routes/cybersecurite/test-intrusion-audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilItStrategiqueRoute = ConseilItStrategiqueRouteImport.update({
  id: '/conseil-it-strategique',
  path: '/conseil-it-strategique',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingRecrutementItRoute = SourcingRecrutementItRouteImport.update({
  id: '/sourcing-recrutement-it',
  path: '/sourcing-recrutement-it',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecuriteIndexRoute = CybersecuriteIndexRouteImport.update({
  id: '/cybersecurite/',
  path: '/cybersecurite/',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecuriteGrcRoute = CybersecuriteGrcRouteImport.update({
  id: '/cybersecurite/grc',
  path: '/cybersecurite/grc',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecuriteSecuriteManageeRoute =
  CybersecuriteSecuriteManageeRouteImport.update({
    id: '/cybersecurite/securite-managee',
    path: '/cybersecurite/securite-managee',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybersecuriteTestIntrusionAuditRoute =
  CybersecuriteTestIntrusionAuditRouteImport.update({
    id: '/cybersecurite/test-intrusion-audit',
    path: '/cybersecurite/test-intrusion-audit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conseil-it-strategique': typeof ConseilItStrategiqueRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing-recrutement-it': typeof SourcingRecrutementItRoute
  '/cybersecurite/grc': typeof CybersecuriteGrcRoute
  '/cybersecurite/securite-managee': typeof CybersecuriteSecuriteManageeRoute
  '/cybersecurite/test-intrusion-audit': typeof CybersecuriteTestIntrusionAuditRoute
  '/cybersecurite/': typeof CybersecuriteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conseil-it-strategique': typeof ConseilItStrategiqueRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing-recrutement-it': typeof SourcingRecrutementItRoute
  '/cybersecurite/grc': typeof CybersecuriteGrcRoute
  '/cybersecurite/securite-managee': typeof CybersecuriteSecuriteManageeRoute
  '/cybersecurite/test-intrusion-audit': typeof CybersecuriteTestIntrusionAuditRoute
  '/cybersecurite': typeof CybersecuriteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conseil-it-strategique': typeof ConseilItStrategiqueRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing-recrutement-it': typeof SourcingRecrutementItRoute
  '/cybersecurite/grc': typeof CybersecuriteGrcRoute
  '/cybersecurite/securite-managee': typeof CybersecuriteSecuriteManageeRoute
  '/cybersecurite/test-intrusion-audit': typeof CybersecuriteTestIntrusionAuditRoute
  '/cybersecurite/': typeof CybersecuriteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conseil-it-strategique'
    | '/faq'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/sourcing-recrutement-it'
    | '/cybersecurite/grc'
    | '/cybersecurite/securite-managee'
    | '/cybersecurite/test-intrusion-audit'
    | '/cybersecurite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conseil-it-strategique'
    | '/faq'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/sourcing-recrutement-it'
    | '/cybersecurite/grc'
    | '/cybersecurite/securite-managee'
    | '/cybersecurite/test-intrusion-audit'
    | '/cybersecurite'
  id:
    | '__root__'
    | '/'
    | '/conseil-it-strategique'
    | '/faq'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/sourcing-recrutement-it'
    | '/cybersecurite/grc'
    | '/cybersecurite/securite-managee'
    | '/cybersecurite/test-intrusion-audit'
    | '/cybersecurite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConseilItStrategiqueRoute: typeof ConseilItStrategiqueRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcingRecrutementItRoute: typeof SourcingRecrutementItRoute
  CybersecuriteGrcRoute: typeof CybersecuriteGrcRoute
  CybersecuriteSecuriteManageeRoute: typeof CybersecuriteSecuriteManageeRoute
  CybersecuriteTestIntrusionAuditRoute: typeof CybersecuriteTestIntrusionAuditRoute
  CybersecuriteIndexRoute: typeof CybersecuriteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseil-it-strategique': {
      id: '/conseil-it-strategique'
      path: '/conseil-it-strategique'
      fullPath: '/conseil-it-strategique'
      preLoaderRoute: typeof ConseilItStrategiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing-recrutement-it': {
      id: '/sourcing-recrutement-it'
      path: '/sourcing-recrutement-it'
      fullPath: '/sourcing-recrutement-it'
      preLoaderRoute: typeof SourcingRecrutementItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurite/': {
      id: '/cybersecurite/'
      path: '/cybersecurite'
      fullPath: '/cybersecurite/'
      preLoaderRoute: typeof CybersecuriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurite/grc': {
      id: '/cybersecurite/grc'
      path: '/cybersecurite/grc'
      fullPath: '/cybersecurite/grc'
      preLoaderRoute: typeof CybersecuriteGrcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurite/securite-managee': {
      id: '/cybersecurite/securite-managee'
      path: '/cybersecurite/securite-managee'
      fullPath: '/cybersecurite/securite-managee'
      preLoaderRoute: typeof CybersecuriteSecuriteManageeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurite/test-intrusion-audit': {
      id: '/cybersecurite/test-intrusion-audit'
      path: '/cybersecurite/test-intrusion-audit'
      fullPath: '/cybersecurite/test-intrusion-audit'
      preLoaderRoute: typeof CybersecuriteTestIntrusionAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConseilItStrategiqueRoute: ConseilItStrategiqueRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcingRecrutementItRoute: SourcingRecrutementItRoute,
  CybersecuriteGrcRoute: CybersecuriteGrcRoute,
  CybersecuriteSecuriteManageeRoute: CybersecuriteSecuriteManageeRoute,
  CybersecuriteTestIntrusionAuditRoute: CybersecuriteTestIntrusionAuditRoute,
  CybersecuriteIndexRoute: CybersecuriteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
